name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  linting:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup UTC
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Code Linting
        run: npm run lint

      - name: Type Check
        run: npm run type-check

      - name: Unit Test
        run: npm run test --passWithNoTests
